_wandb:
    value:
        cli_version: 0.23.1
        e:
            goka17hpgghtwytcj51tdormkcltzxiu:
                codePath: src/mlops/train.py
                codePathLocal: src/mlops/train.py
                email: helgamariam@gmail.com
                executable: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/.venv/bin/python3
                git:
                    commit: dec715d2c96880855b6d8e171680083286fdae0c
                    remote: https://github.com/mrarat/DTU-MLops-project.git
                host: mac.students.clients.local
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/src/mlops/train.py
                python: CPython 3.13.11
                root: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project
                startedAt: "2026-01-15T10:42:38.044483Z"
                writerId: goka17hpgghtwytcj51tdormkcltzxiu
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
entity:
    value: playing-card-classifier
method:
    value: bayes
metric:
    value:
        goal: minimize
        name: validation_loss
parameters:
    value:
        batch_size:
            values:
                - 16
                - 32
                - 64
        epochs:
            values:
                - 5
                - 10
                - 15
        lr:
            distribution: log_uniform
            max: 0.1
            min: 0.0001
        seed:
            values:
                - 42
program:
    value: train.py
project:
    value: mlops-group-42
run_cap:
    value: 10
