_wandb:
    value:
        cli_version: 0.23.1
        e:
            41yytewnoycz21eb2tgux1r57fvabrzd:
                codePath: src/mlops/train.py
                codePathLocal: src/mlops/train.py
                email: helgamariam@gmail.com
                executable: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/.venv/bin/python3
                git:
                    commit: dec715d2c96880855b6d8e171680083286fdae0c
                    remote: https://github.com/mrarat/DTU-MLops-project.git
                host: mac.students.clients.local
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/src/mlops/train.py
                python: CPython 3.13.11
                root: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project
                startedAt: "2026-01-15T11:52:33.773763Z"
                writerId: 41yytewnoycz21eb2tgux1r57fvabrzd
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
hyperparameters:
    value:
        batch_size: 32
        epochs: 10
        lr: 0.001
        seed: 42
