program: src/mlops/train.py
project: playing-card-classifier
entity: mlops-group-42
method: bayes
metric:
  goal: maximize
  name: eval/best_avg_accuracy
parameters:
  hyperparameters.lr:
    max: 0.003
    min: 0.00003
    distribution: log_uniform_values
  hyperparameters.r_weight:
    values: [0.3, 0.4, 0.5, 0.6, 0.7]
  hyperparameters.batch_size:
    values: [16, 32, 64]
  hyperparameters.epochs:
    values: [5, 10, 15]
  hyperparameters.seed:
    values: [42]
run_cap: 10

command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - ${args_no_hyphens}
