_wandb:
    value:
        cli_version: 0.23.1
        e:
            dpqtzcc1kt6yhwcv8820f88aylwms6lx:
                codePath: src/mlops/evaluate.py
                codePathLocal: src/mlops/evaluate.py
                email: helgamariam@gmail.com
                executable: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/.venv/bin/python3
                git:
                    commit: 49e68aae58122d4097cb8968e68c93d67fffdf0b
                    remote: https://github.com/mrarat/DTU-MLops-project.git
                host: mac.students.clients.local
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project/src/mlops/evaluate.py
                python: CPython 3.13.11
                root: /Users/helgamariamagnusdottir/Documents/dtu/ml_ops/DTU-MLops-project
                startedAt: "2026-01-09T14:07:28.433850Z"
                writerId: dpqtzcc1kt6yhwcv8820f88aylwms6lx
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
checkpoint:
    value: null
device:
    value: mps
